spring.application.name=visa-backoffice

spring.datasource.url=jdbc:postgresql://localhost:5432/visa_gestion?currentSchema=dev
spring.datasource.username=app_dev
spring.datasource.password=dev_pwd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=dev
spring.jpa.properties.hibernate.format_sql=true
